# Tutorial OpenCV do pyimagemsearch

## Manipulação básica de imagens

In [1]:
!pip install imutils

In [1]:
#Importando bibliotecas
import imutils
import cv2
import matplotlib.pyplot as plt

%matplotlib inline

### Lendo imagem

In [2]:
#Lendo a primeira imagem

image = cv2.imread('jp.png')
(h, w, d) = image.shape
print('width={}, heigth={}, depth={}'.format(h,w,d))

width=322, heigth=600, depth=3


### Mostrando imagem

In [3]:
#Mostrando a imagem
cv2.imshow("image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()
#Se eu quisesse mostrar inline, teria que usar o matplotlib

### Cortando imagem

In [4]:
#Pegando uma fatia da imagem, uma região de interesse
roi = image[60:160, 320:420] #os números dos pixeis que eu quero pegar em ambos os eixos
cv2.imshow("Região de Interesse", roi)
cv2.waitKey(0)
cv2.destroyAllWindows()


### Redimensionando imagem

In [5]:
#Redimensionando imagens
resized = cv2.resize(image, (200,200))
cv2.imshow("Imagem redimensionada", resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
#Redimensionando a imagem mantendo a proporção
#já sabendo que eu quero um width de 300px
r = 300.0/w
dim = (300, int(h*r))
resized = cv2.resize(image, dim)
cv2.imshow("Imagem redimensionada proporcional", resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
#Tem uma maneira mais fácil de fazer o redimensionamento usando a lib imutils
resized = imutils.resize(image, width = 300)
cv2.imshow("Imagem redimensionada proporcional com imutils", resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Rotacionando imagem

In [8]:
#Rotacionando imagens
#primeiro, rotacionar a imagem 45 graus no sentido horário usando o opencv
#inicialmente temos que calcular onde fica o centro da imagem
center = (w // 2, h // 2)
M = cv2.getRotationMatrix2D(center, -45, 1.0) #Esse 1.0 é um zoom da imagem, 1.0 mantém o tamanho original
rotated = cv2.warpAffine(image, M, (w, h))
cv2.imshow("Imagem rotacionada", rotated)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
#fazendo a mesma coisa com o imutils
urotated = imutils.rotate(image, -45)
cv2.imshow("Imagem rotacionada com imutils", urotated)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
#outra maneira de rotacionar a imagem com o imutils sem cortar a imagem
urotated = imutils.rotate_bound(image, 45)
cv2.imshow("Imagem rotacionada com imutils sem cortes", urotated)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Aplicando blur

In [11]:
#Usando o efeito Blur na imagem
#Algumas vezes é necessário usar o efeito blur para que o algoritmo possa entender de maneira mais fácil o que está na imagem, pois retira o ruído
blurred = cv2.GaussianBlur(image, (11,11), 0) # apply a Gaussian blur with a 11x11 kernel to the image to smooth it
cv2.imshow("Imagem com blur", blurred)
cv2.waitKey(0)
cv2.destroyAllWindows()
#Quanto maior o tamanho do kernel, mais o efeito de blur ficará aparente na nova imagem

### Desenhar na imagem
Toda vez que se desenha na imagem, o arquivo o qual se está fazendo referência é motificado, sendo assim é ideal sempre fazer uma cópia do arquivo antes de qualquer coisa

In [12]:
#Retângulo
output = image.copy()
cv2.rectangle(output, (320, 60), (420, 160), (0, 0, 255), 2) #(320, 60) é o pixel onde o retângulo começa, (420, 160) é onde o retângulo acaba, (0, 0, 255) é a cor da linha no padrão BGR
cv2.imshow("Rectangle", output)                              #e por último o valor 2 é a grossura da linha, se o valor fosse negativo, seria um retângulo sólido
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
#Círuclo
output = image.copy()
cv2.circle(output, (300, 150), 20, (255, 0, 0), -1) #(300, 150) é o centro do círculo, 20 é o raio, o resto é o mesmo padrão do retângulo
cv2.imshow("Circle", output)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
#Linha
output = image.copy()
cv2.line(output, (60, 20), (400, 200), (0, 0, 255), 5) #mesmos parâmetros do retângulo
cv2.imshow("Line", output)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
#Texto
output = image.copy()
cv2.putText(output, "OpenCV + JP", (10, 25), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2) #(10, 25) é o ponto de início do texto, 0.7 é o tamanho do fonte, seguidos pela cor e grossura
cv2.imshow("Texto", output)
cv2.waitKey(0)
cv2.destroyAllWindows()

_______________________________________________________________________________

## Contando objetos

### Lendo imagem

In [16]:
image = cv2.imread("tetris_blocks.png")
cv2.imshow("Blocos", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Convertendo cores

In [17]:
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow("Blocos em cinza", gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Detecção de bordas

In [18]:
edge = cv2.Canny(gray, 30, 150) #30 e 150 são os valores mínimos e máximos de threshold
cv2.imshow("Edged", edge)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Thresholding

In [19]:
thresh = cv2.threshold(gray, 225, 255, cv2.THRESH_BINARY_INV)[1] #225 significa que todos os valores menores que 225 virarão 0, e os valores entre 225 e 255 irão para 255
cv2.imshow("Thresh", thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Detectando e desenhando os contornos

In [20]:
cnts = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
cnts = imutils.grab_contours(cnts)
output = image.copy()

for c in cnts:
    cv2.drawContours(output, [c], -1, (240, 0, 159), 3)
    cv2.imshow("Contornos", output)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

#### Somando com o uso de texto

In [21]:
#desenhando o número total de contornos achados
text = "Achei {} contornos!".format(len(cnts))
cv2.putText(output, text, (10, 25),  cv2.FONT_HERSHEY_SIMPLEX, 0.7, (240, 0, 159), 2)
cv2.imshow("Contorno com plus", output)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Erosão e dilatações
São usados para reduzir ruído em imagens binárias

In [22]:
mask = thresh.copy()
mask = cv2.erode(mask, None, iterations = 5)
cv2.imshow("Com erosão", mask)
cv2.waitKey(0)
cv2.destroyAllWindows()
#Com isso a região de contorno ficou levemente menor

In [23]:
mask = thresh.copy()
mask = cv2.dilate(mask, None, iterations=5)
cv2.imshow("Com dilatação", mask)
cv2.waitKey(0)
cv2.destroyAllWindows()
#Com isso a região de contorno ficou maior

#### Porque usar mask? Usando mask, podemos ignorar tudo que não está na nossa área de interesse para trabalhar

In [24]:
mask = thresh.copy()
output = cv2.bitwise_and(image, image, mask=mask)
cv2.imshow("Output", output)
cv2.waitKey(0)
cv2.destroyAllWindows()

_____________________________________________________________________________________________________

## Achando extremidades

In [25]:
hand = cv2.imread("hand_01.png")
cv2.imshow("Mão original", hand)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [26]:
#deixando cinza
gray = cv2.cvtColor(hand, cv2.COLOR_BGR2GRAY) 
cv2.imshow("Mão cinza", gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [27]:
#aplicando blur
gray = cv2.GaussianBlur(gray, (5,5), 0)
cv2.imshow("Mão cinza com blur", gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [28]:
#definindo threshoold e fazendo erosão e dilatações para retirar o máximo de ruídos
thresh = cv2.threshold(gray, 45,255, cv2.THRESH_BINARY)[1]
thresh = cv2.erode(thresh, None, iterations=2)
thresh = cv2.dilate(thresh, None, iterations=2)
cv2.imshow("Mão com threshold, erosão e dilatação", thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [29]:
#achando cortonos e retornando o maior deles
cnts = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
cnts = imutils.grab_contours(cnts)
c = max(cnts, key=cv2.contourArea)
print(c) #array de pixels

[[[185  73]]

 [[184  74]]

 [[180  74]]

 ...

 [[193  74]]

 [[190  74]]

 [[189  73]]]


In [30]:
#determinando os pontos extremos
extLeft = tuple(c[c[:, :, 0].argmin()][0])
extRight = tuple(c[c[:, :, 0].argmax()][0])
extTop = tuple(c[c[:, :, 1].argmin()][0])
extBot = tuple(c[c[:, :, 1].argmax()][0])

In [31]:
#Desenhando o contorno da mão e os pontos
cv2.drawContours(hand, [c], -1, (0, 255, 255), 2)
cv2.circle(hand, extLeft, 8, (0, 0, 255), -1)
cv2.circle(hand, extRight, 8, (0, 255, 0), -1)
cv2.circle(hand, extTop, 8, (255, 0, 0), -1)
cv2.circle(hand, extBot, 8, (255, 255, 0), -1)

cv2.imshow("Resultado", hand)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [32]:
def desenharContorno(image):
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) 
    thresh = cv2.threshold(gray, 45,255, cv2.THRESH_BINARY)[1]
    thresh = cv2.erode(thresh, None, iterations=2)
    thresh = cv2.dilate(thresh, None, iterations=2)
    cnts = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    cnts = imutils.grab_contours(cnts)
    c = max(cnts, key=cv2.contourArea)
    extLeft = tuple(c[c[:, :, 0].argmin()][0])
    extRight = tuple(c[c[:, :, 0].argmax()][0])
    extTop = tuple(c[c[:, :, 1].argmin()][0])
    extBot = tuple(c[c[:, :, 1].argmax()][0])
    cv2.drawContours(hand, [c], -1, (0, 255, 255), 2)
    cv2.circle(image, extLeft, 8, (0, 0, 255), -1)
    cv2.circle(image, extRight, 8, (0, 255, 0), -1)
    cv2.circle(image, extTop, 8, (255, 0, 0), -1)
    cv2.circle(image, extBot, 8, (255, 255, 0), -1)

    cv2.imshow("Resultado", image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [33]:
hand = cv2.imread("hand_02.png")

In [34]:
desenharContorno(hand)

---------------------------------------------------------------------------

## Mudando perspectiva

In [35]:
import numpy as np
import cv2

In [36]:
np.zeros((4, 2), dtype = "float32")

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [37]:
def order_points(pts):
    rect = np.zeros((4,2), dtype = "float32")
    s = pts.sum(axis = 1)
    rect[0] = pts[np.argmin(s)]
    rect[2] = pts[np.argman(s)]
    
    diff = np.diff(pts, axis = 1)
    rect[1] = pts[np.argmin(diff)]
    rect[3] = pts[np.argmax(diff)]
    
    return rect

In [38]:
def four_point_transformation(image, pts):
    #obtendo informações da função acima
    rect = order_points(pts)
    (tl, tr, br, bl) = rect
    
    #definindo a largura real da imagem usando pitagoras nos pontos de baixo e nos pontos de cima e pegando o maior resultado
    widthA = np.sqrt(((br[0] - bl[0])**2) + ((br[1] - bl[1])**2))
    widthB = np.sqrt(((tr[0] - tl[0])**2) + ((tr[1] - tl[1])**2))
    maxWidth = max(int(widthA), int(widthB))
    
    #Fazendo o mesmo que foi feito acima, só que agora para pegar a altura real
    heightA = np.sqrt(((tr[0] - br[0])**2) + ((tr[1] + br[1])**2))
    heightB = np.sqrt(((tl[0] - bl[0])**2) + ((tl[1] + bl[1])**2))
    maxHeight = max(int(heightA), int(heightB))
    
    #agora, definindo ao novos pontos limites da figura que será transformada
    dst = np.array(
    [0, 0]
    [maxWidth - 1, 0]
    [maxWidth -1, maxHeight -1]
    [0, maxHeight -1], dtype = "float32")
    
    #Computando a mudança de perspectiva e aplicando
    M = cv2.getPerspectiveTransform(rect, dst) #primeiro, pontos originais, após, novos pontos de limite
    warped = cv2.warpPerspective(image, M, (maxWidth, maxHeight))
    
    #retornando o resultado da transformação
    return warped

In [39]:
card = cv2.imread("card.png")
card = imutils.resize(card, width=300)

In [40]:
cv2.imshow("Original", card)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [41]:
grayCard = cv2.cvtColor(card, cv2.COLOR_BGR2GRAY)
cv2.imshow("Original", grayCard)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [42]:
thresh = cv2.threshold(grayCard, 200,255, cv2.THRESH_BINARY)[1]
thresh = cv2.erode(thresh, None, iterations=2)
thresh = cv2.dilate(thresh, None, iterations=2)
cv2.imshow("Mão com threshold, erosão e dilatação", thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [43]:
#achando cortonos e retornando o maior deles
cnts = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
cnts = imutils.grab_contours(cnts)
c = max(cnts, key=cv2.contourArea)

In [44]:
#determinando os pontos extremos
extLeft = tuple(c[c[:, :, 0].argmin()][0])
extRight = tuple(c[c[:, :, 0].argmax()][0])
extTop = tuple(c[c[:, :, 1].argmin()][0])
extBot = tuple(c[c[:, :, 1].argmax()][0])

In [45]:
#Desenhando o contorno da mão e os pontos
cv2.drawContours(card, [c], -1, (0, 255, 255), 2)
cv2.circle(card, extLeft, 8, (0, 0, 255), -1)
cv2.circle(card, extRight, 8, (0, 255, 0), -1)
cv2.circle(card, extTop, 8, (255, 0, 0), -1)
cv2.circle(card, extBot, 8, (255, 255, 0), -1)

cv2.imshow("Resultado", card)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [46]:
for c in cnts:
    cv2.drawContours(card, [c], -1, (240, 0, 159), 3)
    cv2.imshow("Contornos", card)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [47]:
desenharContorno(card)

#### Não funcionou muito bem, pois a imagem vem com algum problema e não to com muita paciencia de resolver agora

-------------------

### Scanner de cartão resposta

In [1]:
# import the necessary packages
from imutils.perspective import four_point_transform
from imutils import contours
import numpy as np
#import argparse
import imutils
import cv2
# construct the argument parse and parse the arguments
#ap = argparse.ArgumentParser()
#ap.add_argument("-i", "--image", required=True,
#	help="path to the input image")
#args = vars(ap.parse_args())
# define the answer key which maps the question number
# to the correct answer
ANSWER_KEY = {0: 1, 1: 4, 2: 0, 3: 3, 4: 1}

In [2]:
# load the image, convert it to grayscale, blur it
# slightly, then find edges
image = cv2.imread('omr_test_01.png')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
blurred = cv2.GaussianBlur(gray, (5, 5), 0)
edged = cv2.Canny(blurred, 75, 200)

In [3]:
cv2.imshow("Resultado", edged)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
# find contours in the edge map, then initialize
# the contour that corresponds to the document
cnts = cv2.findContours(edged.copy(), cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
cnts = imutils.grab_contours(cnts)
docCnt = None
# ensure that at least one contour was found
if len(cnts) > 0:
    # sort the contours according to their size in
    # descending order
    cnts = sorted(cnts, key=cv2.contourArea, reverse=True)
    # loop over the sorted contours
    for c in cnts:
        # approximate the contour
        peri = cv2.arcLength(c, True)
        approx = cv2.approxPolyDP(c, 0.02 * peri, True)
        # if our approximated contour has four points,
        # then we can assume we have found the paper
        if len(approx) == 4:
            docCnt = approx
            break

In [6]:
test = image.copy()
cv2.drawContours(test,docCnt, -1,  (0, 255, 255), 3)

array([[[ 48,  72,  81],
        [ 51,  76,  87],
        [ 53,  76,  93],
        ...,
        [ 61,  88, 104],
        [ 62,  88, 103],
        [ 60,  89, 103]],

       [[ 48,  75,  84],
        [ 46,  74,  85],
        [ 51,  78,  94],
        ...,
        [ 62,  89, 104],
        [ 59,  86,  99],
        [ 56,  84,  99]],

       [[ 55,  77,  92],
        [ 49,  75,  88],
        [ 49,  73,  87],
        ...,
        [ 57,  84,  98],
        [ 65,  94, 104],
        [ 65,  95, 107]],

       ...,

       [[ 44,  69,  83],
        [ 44,  72,  84],
        [ 50,  76,  87],
        ...,
        [ 59,  83,  94],
        [ 60,  84,  95],
        [ 59,  85,  97]],

       [[ 49,  73,  87],
        [ 43,  69,  84],
        [ 42,  67,  82],
        ...,
        [ 52,  78,  88],
        [ 63,  90, 101],
        [ 64,  90, 102]],

       [[ 45,  68,  76],
        [ 48,  73,  88],
        [ 42,  67,  84],
        ...,
        [ 48,  77,  89],
        [ 62,  91, 103],
        [ 69,  95, 107]]

In [7]:
cv2.imshow("Resultado", test)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
# apply a four point perspective transform to both the
# original image and grayscale image to obtain a top-down
# birds eye view of the paper
paper = four_point_transform(image, docCnt.reshape(4, 2))
warped = four_point_transform(gray, docCnt.reshape(4, 2))

In [9]:
cv2.imshow("Resultado", paper)
cv2.waitKey(0)
cv2.destroyAllWindows()

cv2.imshow("Resultado", warped)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
# apply Otsu's thresholding method to binarize the warped
# piece of paper
thresh = cv2.threshold(warped, 0, 255, cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)[1]

In [11]:
cv2.imshow("Resultado", thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
# find contours in the thresholded image, then initialize
# the list of contours that correspond to questions
cnts = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL,
	cv2.CHAIN_APPROX_SIMPLE)
cnts = imutils.grab_contours(cnts)
questionCnts = []
# loop over the contours
for c in cnts:
    # compute the bounding box of the contour, then use the
    # bounding box to derive the aspect ratio
    (x, y, w, h) = cv2.boundingRect(c)
    ar = w / float(h)
    # in order to label the contour as a question, region
    # should be sufficiently wide, sufficiently tall, and
    # have an aspect ratio approximately equal to 1
    if w >= 20 and h >= 20 and ar >= 0.9 and ar <= 1.1:
        questionCnts.append(c)

In [13]:
test = paper.copy()
cv2.drawContours(test, questionCnts, -1, (0, 0, 255), 3)
cv2.imshow("Resultado", test)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
# sort the question contours top-to-bottom, then initialize
# the total number of correct answers
questionCnts = contours.sort_contours(questionCnts,
    method="top-to-bottom")[0]
correct = 0
# each question has 5 possible answers, to loop over the
# question in batches of 5
for (q, i) in enumerate(np.arange(0, len(questionCnts), 5)):
    # sort the contours for the current question from
    # left to right, then initialize the index of the
    # bubbled answer
    cnts = contours.sort_contours(questionCnts[i:i + 5])[0]
    bubbled = None
    # loop over the sorted contours
    for (j, c) in enumerate(cnts):
        # construct a mask that reveals only the current
        # "bubble" for the question
        mask = np.zeros(thresh.shape, dtype="uint8")
        cv2.drawContours(mask, [c], -1, 255, -1)
        # apply the mask to the thresholded image, then
        # count the number of non-zero pixels in the
        # bubble area
        mask = cv2.bitwise_and(thresh, thresh, mask=mask)
        total = cv2.countNonZero(mask)
        # if the current total has a larger number of total
        # non-zero pixels, then we are examining the currently
        # bubbled-in answer
        if bubbled is None or total > bubbled[0]:
            bubbled = (total, j)
    # initialize the contour color and the index of the
    # *correct* answer
    color = (0, 0, 255)
    k = ANSWER_KEY[q]
    # check to see if the bubbled answer is correct
    if k == bubbled[1]:
        color = (0, 255, 0)
        correct += 1
    # draw the outline of the correct answer on the test
    cv2.drawContours(paper, [cnts[k]], -1, color, 3)

In [16]:
# grab the test taker
score = (correct / 5.0) * 100
print("[INFO] score: {:.2f}%".format(score))
cv2.putText(paper, "{:.2f}%".format(score), (10, 30),
    cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 0, 255), 2)
cv2.imshow("Original", image)
cv2.imshow("Exam", paper)
cv2.waitKey(0)
cv2.destroyAllWindows()

[INFO] score: 80.00%
